### ISSUE TITLE
False positives when parsing scripts

### ISSUE THREAD

**Issue by Nicals** [bbrodriges/pholcidae#12]
While crawling websites with scripts on the page, some false positive can appears.

The issued was found in a text/x-tmpl-jstag script. And I add the output:
http://www.xxx.fr/some-random-stuff/some-random-page/<:itaime.item.url/<:itaime.item.url/><if isDickOrAss>?currentDate=<:sectionTitle.replace(/\//g,'-')/></if>

I'm not sure how this can be solved. In fact, I added a regex to the exclude_links settings. But maybe an option to avoid parsing scripts tags could be helpfull.

**Comment by bbrodriges** [comment]
Should be now fixed in 2.0 version using ```valid_mimes``` option
